name: tods-cd

on: 
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0' ]

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
            fetch-depth: 0
      - uses: actions/setup-dotnet@v1.7.2
        name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Package
        run: dotnet pack --no-build --configuration Release src/Tennis-Open-Data-Standards/Tennis-Open-Data-Standards.csproj --output .
      #- name: Publish the package to nuget.org
      #  run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ORG_AUTH_KEY}} --skip-duplicate
      - name: get-net-sdk-project-versions-action
        uses: naminodarie/get-net-sdk-project-versions-action@v1.1.1
        id: get-version
        with:
          proj-path: src/Tennis-Open-Data-Standards/Tennis-Open-Data-Standards.csproj
      - name: 'Get Previous tag'
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: previoustag
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          from-tag: ${{ steps.previoustag.outputs.tag }}
          to-tag: HEAD
      - name: Create Release
        uses: actions/create-release@latest
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.get-version.outputs.package-version }}
          release_name: ${{ steps.get-version.outputs.package-version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: Upload nuget pacakge
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Tennis-Open-Data-Standards.${{ steps.get-version.outputs.package-version }}.nupkg
          asset_name: Tennis-Open-Data-Standards.${{ steps.get-version.outputs.package-version }}.nupkg
          asset_content_type: application/zip
